export const Colors = {
  // Backgrounds
  bg:          '#080612',
  bgCard:      '#110D20',
  bgCardLight: '#1A1430',
  bgElevated:  '#221A38',

  // Brand
  accent:      '#7F77DD',
  accentLight: '#AFA9EC',
  accentDim:   '#2A2450',
  accentGlow:  '#534AB7',

  // Semantic
  teal:        '#1D9E75',
  tealLight:   '#5DCAA5',
  coral:       '#D85A30',
  amber:       '#EF9F27',
  amberLight:  '#FAC775',

  // Text
  textPrimary:   '#F2F0FA',
  textSecondary: '#9B97B8',
  textMuted:     '#4A4668',
  textHint:      '#2E2A45',

  // UI
  border:      '#1E1A32',
  borderLight: '#2A2545',
  white:       '#FFFFFF',
  black:       '#000000',

  // Status
  success: '#1D9E75',
  error:   '#D85A30',
  warning: '#EF9F27',
};

export const Emotions = {
  joyful: {
    key:        'joyful',
    label:      'Radiating Joy',
    bg:         '#0A1F12',
    card:       '#0F2818',
    accent:     '#1D9E75',
    accentLight:'#5DCAA5',
    glow:       '#1D9E7520',
    energy:     8,
    focus:      7,
    social:     9,
    icon:       '◉',
    summary:    "Your joy is real and you deserve to feel every bit of it today.",
    tasks:      ['Share your energy with someone who needs it', 'Channel this into your most exciting project', 'Do something creative and expressive'],
    rest:       'Ride this wave — but remember to eat and hydrate.',
    social:     "Your social battery is full — reach out to someone you care about.",
    spotify:    'happy upbeat feel good pop',
  },
  calm: {
    key:        'calm',
    label:      'Peacefully Grounded',
    bg:         '#080F1F',
    card:       '#0D1628',
    accent:     '#378ADD',
    accentLight:'#85B7EB',
    glow:       '#378ADD20',
    energy:     5,
    focus:      7,
    social:     5,
    icon:       '◎',
    summary:    "This calm is a gift. Let it carry you through whatever comes today.",
    tasks:      ['Tackle your most important task with full presence', 'Plan your week ahead with clarity', 'Read something that inspires and challenges you'],
    rest:       'Your nervous system is balanced — keep it that way.',
    social:     "You have good energy for meaningful one-on-one conversations today.",
    spotify:    'calm peaceful ambient focus',
  },
  anxious: {
    key:        'anxious',
    label:      'Quietly Anxious',
    bg:         '#1A120A',
    card:       '#221808',
    accent:     '#EF9F27',
    accentLight:'#FAC775',
    glow:       '#EF9F2720',
    energy:     6,
    focus:      3,
    social:     3,
    icon:       '◈',
    summary:    "Anxiety means you care deeply. Let's turn that energy into something useful right now.",
    tasks:      ['Write down exactly what is worrying you — all of it', 'Take 5 slow deep breaths before anything else', 'Go for a 10 minute walk outside without your phone'],
    rest:       'Avoid caffeine today. Your nervous system needs calm.',
    social:     "Keep social interactions small and safe today. One trusted person is enough.",
    spotify:    'calming anxiety relief breathing music',
  },
  stressed: {
    key:        'stressed',
    label:      'Under Pressure',
    bg:         '#1A0F0A',
    card:       '#221508',
    accent:     '#D85A30',
    accentLight:'#F0997B',
    glow:       '#D85A3020',
    energy:     5,
    focus:      3,
    social:     2,
    icon:       '⊗',
    summary:    "You are carrying a lot right now. Let's make the load lighter together.",
    tasks:      ['Write your top 3 priorities — ignore everything else', 'Block one hour of no-interruption focus time', 'Delegate or defer one thing from your list today'],
    rest:       'Step fully away for 10 minutes. It actually helps.',
    social:     "Protect your energy today. It is okay to say no to things.",
    spotify:    'stress relief calm focus deep work',
  },
  burnt_out: {
    key:        'burnt_out',
    label:      'Running On Empty',
    bg:         '#0F0D1A',
    card:       '#151220',
    accent:     '#534AB7',
    accentLight:'#AFA9EC',
    glow:       '#534AB720',
    energy:     2,
    focus:      2,
    social:     2,
    icon:       '○',
    summary:    "Your mind and body are asking for rest. That is not weakness — that is wisdom.",
    tasks:      ['Do absolutely nothing for 20 full minutes', 'Cancel or postpone one non-essential commitment', 'Sleep or rest without any guilt whatsoever'],
    rest:       'Rest is not laziness right now. It is survival.',
    social:     "Complete solo time today. You have nothing left to give and that is okay.",
    spotify:    'healing rest gentle soft instrumental',
  },
  focused: {
    key:        'focused',
    label:      'In The Zone',
    bg:         '#091A0F',
    card:       '#0D2214',
    accent:     '#639922',
    accentLight:'#97C459',
    glow:       '#63992220',
    energy:     7,
    focus:      9,
    social:     4,
    icon:       '◆',
    summary:    "You are in a powerful state right now. Let's protect it and make the most of it.",
    tasks:      ['Start your hardest most important task immediately', 'Put your phone completely on silent right now', 'Set a 90 minute deep work timer and begin'],
    rest:       'Break every 90 minutes. Focus compounds, fatigue does not.',
    social:     "Protect this focus state. Defer non-urgent conversations to later.",
    spotify:    'deep focus concentration lo-fi beats',
  },
  sad: {
    key:        'sad',
    label:      'Carrying Sadness',
    bg:         '#080D1A',
    card:       '#0A1222',
    accent:     '#185FA5',
    accentLight:'#85B7EB',
    glow:       '#185FA520',
    energy:     3,
    focus:      3,
    social:     2,
    icon:       '◐',
    summary:    "Sadness is valid and real. It will not last forever. Be gentle with yourself today.",
    tasks:      ['Text one person you trust right now — just say hi', 'Do one small kind thing for yourself today', 'Watch or read something warm and comforting'],
    rest:       'Extra sleep is medicine right now. Take it without guilt.',
    social:     "One trusted person is better than a crowd today. Reach out to them.",
    spotify:    'comforting sad healing indie emotional',
  },
  angry: {
    key:        'angry',
    label:      'Fired Up',
    bg:         '#1A0808',
    card:       '#220D0D',
    accent:     '#E24B4A',
    accentLight:'#F09595',
    glow:       '#E24B4A20',
    energy:     7,
    focus:      2,
    social:     2,
    icon:       '◉',
    summary:    "Your anger is valid. Let's find a healthy way to move this energy through you.",
    tasks:      ['Write down exactly what triggered this — uncensored', 'Do 20 jumping jacks or push-ups to release the energy', 'Wait 10 minutes before responding to anything important'],
    rest:       'Physical movement will help more than anything right now.',
    social:     "Wait before responding to people. You will say something you mean more clearly later.",
    spotify:    'intense workout energy release music',
  },
  excited: {
    key:        'excited',
    label:      'Buzzing With Energy',
    bg:         '#1A1508',
    card:       '#221C0A',
    accent:     '#BA7517',
    accentLight:'#FAC775',
    glow:       '#BA751720',
    energy:     9,
    focus:      6,
    social:     8,
    icon:       '◈',
    summary:    "This excitement is fuel. Let's point it at something that really matters to you.",
    tasks:      ['Channel this energy into your biggest most important goal', 'Start that thing you have been putting off for too long', 'Share your excitement with someone who will match it'],
    rest:       'Ride the wave but do not burn yourself out in one day.',
    social:     "Your energy is magnetic right now. Connect with your most ambitious people.",
    spotify:    'hype energetic pump up motivated',
  },
  lonely: {
    key:        'lonely',
    label:      'Feeling Alone',
    bg:         '#0A0D1A',
    card:       '#0F1222',
    accent:     '#534AB7',
    accentLight:'#AFA9EC',
    glow:       '#534AB720',
    energy:     4,
    focus:      4,
    social:     1,
    icon:       '◌',
    summary:    "Loneliness is temporary. One small genuine connection can shift everything today.",
    tasks:      ['Reach out to one friend you have not spoken to in a while', 'Go somewhere with other people — a cafe or park', 'Join one online community around something you love'],
    rest:       'Being around people — even strangers — can help.',
    social:     "Take one small step toward connection today. Even a short message counts.",
    spotify:    'warm comforting indie folk acoustic',
  },
  grateful: {
    key:        'grateful',
    label:      'Heart Full',
    bg:         '#0A1A10',
    card:       '#0F2215',
    accent:     '#1D9E75',
    accentLight:'#5DCAA5',
    glow:       '#1D9E7520',
    energy:     7,
    focus:      6,
    social:     8,
    icon:       '◉',
    summary:    "Gratitude is one of the most powerful emotional states. Let it multiply today.",
    tasks:      ['Write 5 specific things you are grateful for right now', 'Tell one person today exactly why you appreciate them', 'Do something generous for someone without expecting anything back'],
    rest:       'You are in a wonderful state. Protect it by staying present.',
    social:     "Share your positive energy — it will come back to you multiplied.",
    spotify:    'joyful grateful feel good uplifting',
  },
  overwhelmed: {
    key:        'overwhelmed',
    label:      'Too Much At Once',
    bg:         '#150A1A',
    card:       '#1C0F22',
    accent:     '#993556',
    accentLight:'#ED93B1',
    glow:       '#99355620',
    energy:     4,
    focus:      2,
    social:     2,
    icon:       '⊕',
    summary:    "Everything feels like too much right now. Let's simplify everything together.",
    tasks:      ['Pick just ONE task and ignore absolutely everything else', 'Ask for help with something you are struggling with', 'Break your biggest problem into 3 tiny manageable steps'],
    rest:       'Overwhelm feeds on complexity. Simplify everything you can.',
    social:     "Be honest with people about your capacity today. Real friends will understand.",
    spotify:    'calm overwhelm relief peace meditation',
  },
  hopeful: {
    key:        'hopeful',
    label:      'Looking Forward',
    bg:         '#08101A',
    card:       '#0D1822',
    accent:     '#378ADD',
    accentLight:'#B5D4F4',
    glow:       '#378ADD20',
    energy:     6,
    focus:      6,
    social:     6,
    icon:       '◎',
    summary:    "Hope is one of the most powerful forces there is. Let's take one real step today.",
    tasks:      ['Take one concrete step toward what you are hoping for', 'Write down your clearest vision of where you want to be', 'Research one thing that will help you get there faster'],
    rest:       'Stay grounded while you dream. Rest fuels the journey.',
    social:     "Connect with someone who shares your vision or ambition today.",
    spotify:    'hopeful inspiring uplifting forward',
  },
  tired: {
    key:        'tired',
    label:      'Quietly Exhausted',
    bg:         '#0F0F0F',
    card:       '#141414',
    accent:     '#888780',
    accentLight:'#B4B2A9',
    glow:       '#88878020',
    energy:     2,
    focus:      3,
    social:     3,
    icon:       '◑',
    summary:    "Your body is speaking clearly. It needs rest and you should listen.",
    tasks:      ['Take a 20 minute nap if you possibly can', 'Reduce your task list to just the single most critical thing', 'Go to bed at least one hour earlier than usual tonight'],
    rest:       'Sleep is not optional right now. It is the most productive thing you can do.',
    social:     "Keep interactions light and brief today. Your energy is precious.",
    spotify:    'gentle tired sleepy calm soft',
  },
  confused: {
    key:        'confused',
    label:      'Finding My Way',
    bg:         '#0F0D1A',
    card:       '#151220',
    accent:     '#7F77DD',
    accentLight:'#CECBF6',
    glow:       '#7F77DD20',
    energy:     5,
    focus:      3,
    social:     4,
    icon:       '◎',
    summary:    "Confusion is always the first step toward clarity. You are closer than you think.",
    tasks:      ['Write down exactly what is confusing you — get it out', 'Talk to one person you trust and respect about it', 'Step away for an hour and come back with fresh eyes'],
    rest:       'A rested mind finds answers that a tired one cannot.',
    social:     "One wise conversation could unlock everything. Who do you trust most?",
    spotify:    'clarity calm thinking ambient focus',
  },
};

export function detectEmotion(text) {
  const t = text.toLowerCase();
  const scores = {};

  const patterns = {
    joyful:      /happy|great|amazing|wonderful|joy|fantastic|love|blessed|best|perfect|brilliant|thrilled/g,
    calm:        /calm|peace|relax|quiet|serene|still|gentle|okay|fine|good|settled/g,
    anxious:     /anxious|anxiety|nervous|worry|worried|scared|fear|panic|dread|uneasy/g,
    stressed:    /stress|stressed|pressure|deadline|overwhelm|too much|swamped|rushing|behind/g,
    burnt_out:   /burnt|burnout|exhausted|drained|empty|done|finished|cant anymore|no more|used up/g,
    focused:     /focus|focused|productive|working|concentrate|flow|zone|sharp|clear|determined/g,
    sad:         /sad|upset|cry|depressed|down|low|unhappy|grief|lost|blue|heartbroken|miss/g,
    angry:       /angry|anger|mad|furious|frustrated|irritated|annoyed|rage|hate|fed up/g,
    excited:     /excited|thrilled|pumped|hyped|energetic|motivated|fired up|cant wait|stoked/g,
    lonely:      /lonely|alone|isolated|nobody|no one|missing people|left out|invisible/g,
    grateful:    /grateful|thankful|blessed|appreciate|gratitude|fortunate|lucky/g,
    overwhelmed: /overwhelmed|too much|cant cope|drowning|buried|swamped|everything at once/g,
    hopeful:     /hopeful|hope|optimistic|looking forward|positive|better|excited about future/g,
    tired:       /tired|sleepy|fatigue|exhausted|no energy|weak|worn out|need sleep|cant keep/g,
    confused:    /confused|lost|dont know|unsure|uncertain|unclear|mixed up|no idea|what to do/g,
  };

  for (const [emotion, pattern] of Object.entries(patterns)) {
    const matches = t.match(pattern);
    scores[emotion] = matches ? matches.length : 0;
  }

  const best = Object.entries(scores).sort((a, b) => b[1] - a[1]);
  return best[0][1] > 0 ? best[0][0] : 'calm';
}

export const Typography = {
  h1: { fontSize: 32, fontWeight: '700', color: Colors.textPrimary, letterSpacing: 0.3 },
  h2: { fontSize: 24, fontWeight: '700', color: Colors.textPrimary },
  h3: { fontSize: 18, fontWeight: '600', color: Colors.textPrimary },
  body: { fontSize: 15, fontWeight: '400', color: Colors.textSecondary, lineHeight: 24 },
  small: { fontSize: 13, fontWeight: '400', color: Colors.textSecondary },
  label: { fontSize: 11, fontWeight: '600', color: Colors.textMuted, letterSpacing: 1, textTransform: 'uppercase' },
  mono: { fontSize: 13, fontWeight: '500', color: Colors.textPrimary },
};
